kind: Deployment
apiVersion: apps/v1
metadata:
  name: group18
  namespace: group18
  labels:
    app: group18
spec:
  replicas: 1
  selector:
    matchLabels:
      app: group18
  template:
    metadata:
      labels:
        app: group18
    spec:
      containers:
        - name: group18
          image: jeremykenton23/f1registration:latest
          ports:
            - name: web
              containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: group18
  namespace: group18
spec:
  ports:
    - name: web
      port: 80
      targetPort: web
  selector:
    app: group18
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: group18route
  namespace: group18
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`group18.web.dops.tech`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: group18
          port: 80
  tls:
    certResolver: myresolver
